[package]
name = "test_case"
version = "0.1.0"
authors = ["Yevgen Safronov <yevgen@cloudflare.com>"]
edition = "2021"

publish = false

[dependencies]
lol_html = { path = "../.." }
rand = "0.9.2"
encoding_rs = "0.8.35"

[profile.dev]
opt-level=3
